name: "Newman Tests"
on: [push, pull_request]

jobs:
  build: 
      runs-on: ubuntu-latest
      container: 
        image: postman/newman
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run APT Tests
          run: newman run "Otoscope API.postman_collection.json" -e "kong staging.postman_environment.json"
